---
- hosts: [tst]
  become: true
  gather_facts: false

  vars_files:
    - var-secrets.yml

  tasks:
      - name: Download cloudflared tunnel
        ansible.builtin.shell:
          chdir: /home/foundry
          cmd: |
            curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

      - name: Prepare cloudflared binaries
        ansible.builtin.shell:
          chdir: /home/foundry
          cmd: |
            sudo dpkg -i cloudflared.deb

      - name: Install cloudflared
        ansible.builtin.shell:
          chdir: /home/foundry
          cmd: |
            sudo cloudflared service install {{ cloudflared_token }}