---
- hosts: [all]
  become: false
  gather_facts: false

  vars_files:
    - var-secrets.yml

  tasks:
      - name: Stop foundry
        ansible.builtin.shell:
          cmd: |
            pm2 stop foundry

      - name: Update options.json proxy port
        replace:
          path: /home/foundry/foundrydrive/foundryuserdata/Config/options.json
          regexp: '"proxyPort": null,'
          replace: '"proxyPort": 443,'

      - name: Update options.json SSL enable
        replace:
          path: /home/foundry/foundrydrive/foundryuserdata/Config/options.json
          regexp: '"proxySSL": false,'
          replace: '"proxySSL": true,'

      - name: Update options.json hostname (dev)
        replace:
          path: /home/foundry/foundrydrive/foundryuserdata/Config/options.json
          regexp: '"hostname": null,'
          replace: '"hostname": "dev.foundry.silentcatfart.com",'
        when: inventory_hostname == 'dev.foundry.silentcatfart.com'

      - name: Update options.json hostname (tst)
        replace:
          path: /home/foundry/foundrydrive/foundryuserdata/Config/options.json
          regexp: '"hostname": null,'
          replace: '"hostname": "tst.foundry.silentcatfart.com",'
        when: inventory_hostname == 'tst.foundry.silentcatfart.com'

      - name: Update options.json hostname (prd)
        replace:
          path: /home/foundry/foundrydrive/foundryuserdata/Config/options.json
          regexp: '"hostname": null,'
          replace: '"hostname": "prd.foundry.silentcatfart.com",'
        when: inventory_hostname == 'prd.foundry.silentcatfart.com'                      

      - name: Start foundry
        ansible.builtin.shell:
          cmd: |
            pm2 start foundry