---
- hosts: [all]
  become: false
  gather_facts: false

  vars_files:
    - var-secrets.yml

  tasks:
      - name: Start foundry
        ansible.builtin.shell:
          cmd: |
            pm2 start foundry