## foundry ALL=(ALL) NOPASSWD:ALL in /etc/sudoers.d/ folder
---
- hosts: [new]
  become: true
  gather_facts: false

  vars_files:
    - var-secrets.yml

  tasks:
    - name: Allow foundry user to run all commands without password
      community.general.sudoers:
        name: foundry-all
        state: present
        user: foundry
        runas: ALL
        commands: ALL
        nopassword: true